Adopting the QSTK Numpy tutorials in the iPython

The actual Python tutorial can be found here:
http://wiki.quantsoftware.org/index.php?title=Numpy_Tutorial_1

In [19]:
print 'Importing Numpy'
import numpy as np

Importing Numpy


By convention we load the Numpy library and lets us refer to it by "np"

In [20]:
print 'Creating Arrays...'
# Making arrays in several diffent ways:
zeroArray = np.zeros( (2, 3))
print zeroArray

Creating Arrays...
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [21]:
# or array of ones:
oneArray = np.ones( (2, 3) )
print oneArray

[[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [22]:
# Or filled with junk:
emptyArray = np.empty( (2,3))
print emptyArray

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [23]:
# Create a random array: [0,1]
randomArray = np.random.random( (2,3))
randomArray

array([[ 0.35208989,  0.55905535,  0.13882949],
       [ 0.91915469,  0.39703876,  0.48983442]])

In [24]:
# Create an array by handL
foo = [[1,2,3],
      [4,5,6]]
print foo

[[1, 2, 3], [4, 5, 6]]


In [25]:
myArray = np.array(foo)
print myArray

[[1 2 3]
 [4 5 6]]


In [26]:
print "Reshaping Arrays"

Reshaping Arrays


In [27]:
rangeArray = np.arange(6, 12).reshape( (2,3))
print rangeArray

[[ 6  7  8]
 [ 9 10 11]]


In [28]:
print np.arange(6,12)

[ 6  7  8  9 10 11]


In [29]:
# the reshape method takes the data in an existing array, and stuffs it into
# an array with the given shape and returns it. 

print rangeArray.reshape( (3,2))

[[ 6  7]
 [ 8  9]
 [10 11]]


In [30]:
# The original array does not change:
print rangeArray

[[ 6  7  8]
 [ 9 10 11]]


In [31]:
squareArray = np.arange(1,10).reshape((3,3))
squareArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
print 'Accessing array elements...'

Accessing array elements...


In [33]:
# Accessing an array is also pretty straight forward. You access a specific
# spot in the table by referring to its row and column inside square braces
# after the array:
print rangeArray[0,1]

7


In [34]:
# Note that row and column numbers start from 0, not 1! Numpy also lets you 
# refer to ranges inside an array:
print rangeArray[0, 0:2]

[6 7]


In [35]:
print squareArray[0:2,0:2]

[[1 2]
 [4 5]]


In [37]:
# Like python lists, you can assign values to specific positions, or ranges of values to slices
squareArray[0,:] = np.array(range(1,4))   # set the first row to 1,2,3
squareArray[1,1] = 0                      # set the middle spot to zero
squareArray[2,:] = 1                      # set the last row to ones
print squareArray


[[1 2 3]
 [4 0 6]
 [1 1 1]]


In [41]:
# Something new to numpy arrays is indexing using an array of indices:
fibIndices = np.array([1, 1, 2, 3])
randomRow = np.random.random((10,1)) # an array of 10 random numbers
print randomRow
print randomRow[fibIndices] # the first, first, second and third element of randomRow

[[ 0.7811252 ]
 [ 0.25627124]
 [ 0.69910686]
 [ 0.00705201]
 [ 0.90503387]
 [ 0.20824813]
 [ 0.08794306]
 [ 0.39344388]
 [ 0.65402107]
 [ 0.15499992]]
[[ 0.25627124]
 [ 0.25627124]
 [ 0.69910686]
 [ 0.00705201]]


In [42]:
# You can also use an array of true/false values to index:
boolIndices = np.array( [[ True, False,  True],
                          [False,  True, False],
                          [ True, False,  True]] )
print squareArray[boolIndices]

[1 3 0 1 1]


In [43]:
# It gets a little more complicated with 2D (and higher) arrays.  You need
# two index arrays for a 2D array:
rows = np.array( [[0,0],[2,2]] ) #get the corners of our square array
cols = np.array( [[0,2],[0,2]] )
print squareArray[rows,cols]

[[1 3]
 [1 1]]


In [44]:
boolRows = np.array( [False, True, False] ) # just the middle row
boolCols = np.array( [True, False, True] )  # Not the middle column
print squareArray[boolRows,boolCols]        # [4 6]

[4 6]


In [45]:
print 'Operations on arrays...'

Operations on arrays...


In [46]:
sqAverage = np.average(squareArray)

In [48]:
betterThanAverage = squareArray > sqAverage
print squareArray[betterThanAverage]

[3 4 6]


In [52]:
# Indexing like this can also be used to assign values to elements of the
# array. This is particularly useful if you want to filter an array, say by 
# making sure that all of its values are above/below a certain threshold:

sqStdDev = np.std(squareArray) # returns the standard deviation of all the elements in the fiven array
    

In [53]:
clampedSqArray = np.array(squareArray.copy(), dtype=float)

                                    # make a copy of squareArray that will
                                    # be "clamped". It will only contain
                                    # values within one standard deviation
                                    # of the mean. Values that are too low
                                    # or to high will be set to the min
                                    # and max respectively. We set 
                                    # dtype=float because sqAverage
                                    # and sqStdDev are floating point
                                    # numbers, and we don't want to 
                                    # truncate them down to integers.

In [54]:
clampedSqArray[ (squareArray-sqAverage) > sqStdDev ] = sqAverage+sqStdDev
clampedSqArray[ (squareArray-sqAverage) < -sqStdDev ] = sqAverage-sqStdDev
print clampedSqArray

[[ 1.          2.          3.        ]
 [ 3.90272394  0.31949828  3.90272394]
 [ 1.          1.          1.        ]]


In [55]:
# Multiplying and dividing arrays by numbers does what you'd expect. It
# multiples/divides element-wise
print squareArray * 2

[[ 2  4  6]
 [ 8  0 12]
 [ 2  2  2]]


In [56]:
# Addition works similarly:
print squareArray + np.ones( (3,3) )

[[ 2.  3.  4.]
 [ 5.  1.  7.]
 [ 2.  2.  2.]]


In [57]:
# Multiplying two arrays together (of the same size) is also element wise
print squareArray * np.arange(1,10).reshape( (3,3) )

[[ 1  4  9]
 [16  0 36]
 [ 7  8  9]]


In [ ]:
# Unless you use the dot(...) function, which does matrix multiplication
# from linear algebra:
matA = np.array( [[1,2],[3,4]] )
matB = np.array( [[5,6],[7,8]] )
print np.dot(matA,matB)