# Working with CSV Data


## The Data
The data used is coming from QSTK/Examples/Basic/example-data.csv

In [1]:
%matplotlib inline
import datetime as dt
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [2]:
# Now start with code read in the data and divide it up.
na_data = np.loadtxt('example-data.csv', delimiter=',', skiprows=1)

In [5]:
na_price = na_data[:, 3:]
na_dates = np.int_(na_data[:, 0:3])
ls_symbols = ['$SPX', 'XOM', 'GOOG', 'GLD']

In [6]:
print 'First 5 rows of Price Data:'
print na_price[:5, :]
print 'First 5 rows of Dates:'
print na_dates[:5, :]

First 5 rows of Price Data:
[[ 137.67   87.81  685.19   84.86]
 [ 137.6    88.11  685.33   85.57]
 [ 134.23   86.47  657.     85.13]
 [ 134.11   85.66  649.25   84.77]
 [ 131.95   84.56  631.68   86.78]]
First 5 rows of Dates:
[[2008    1    2]
 [2008    1    3]
 [2008    1    4]
 [2008    1    7]
 [2008    1    8]]


## Plotting the Data